version: '3'
services:
  app:
    build: .
    command: ["./wait-for-it.sh", "mysql", "3306", "--", "npm", "run", "dev"]
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-root}
      - MYSQL_DB=${MYSQL_DB:-prompts}
      - REDIS_HOST=${REDIS_HOST:-redis}
    depends_on:
      - mysql
      - redis
    networks:
      - backend

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DB:-prompts}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
